name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: linux

    steps:
    - name: Download
      run: sudo tar -xvzf ~/Downloads/https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -C /usr/local/bin
    - name: Auth
      run: ngrok config add-authtoken 2IfWZ6EdjqQojALawNDc7DRjmD9_6kWdcpDLX3MfYRLVehnik
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Successfully Created Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
      
    
